apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  labels:
    app: restore-api
data:
  db-connection: 'Server=restoredb-service;Port=5432;Database=store;User Id=appuser;Password=secret;'
